# Generated by Django 5.2 on 2025-05-25 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_updated_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
